### ISSUE TITLE
Issue with Erebus

### ISSUE THREAD

**Issue by Ghostrider231** [Abastro/StellarAPI#10]
Stellar API 1.12.2-0.4.2.7 (This mod) and Erebus-1.0.22 are both incompatible with each other.

This was attempted with only Erebus and Stellar API. So other mods are out of the question.
I'm also using the latest forge version. (14.23.2.2629)

Entering the Erebus Dimension causes the game to load it incorrectly **(It also treats it like I'm still in the overworld)** and doesn't even show the loading screen either. Saving and Quitting while in the broken Erebus Dimension and then loading the infected world again causes it to be unload-able until this mod is removed.

**It doesn't matter if the world is new or not. As this can be repeated very easily. Just get a Erebus Portal (IE. Creating the portal normally or using the /fill ~ ~ ~ ~ ~ ~ erebus:portal command and then enter it with this mod.**

--------------------------------------
**This is the log of the error I got: https://pastebin.com/Ra2apyFF**

**This is while in the broken Erebus Dimension (It pretty much repeats this over and over): https://pastebin.com/RDS1itbG**

--------------------------------------

I use Stellar API for the configurable day/night length. Which is the only mod that I know that doesn't have problems with the sky unlike other mods.

I don't know If problem also persists on other Dimension mods. I know twilight forest is okay with this, but for others I don't know. 

EDIT: Apparently The Betweenlands is also affected by this too: https://github.com/Abastro/StellarAPI/issues/11

The same issue pretty much.

**Comment by Abastro** [comment]
Please try 0.4.2.8 when it comes out.

**Comment by Ghostrider231** [comment]
**Just tried your new version**: Just entered Erebus with this installed and seems to be working perfectly!
The only problem i'm getting so far is the day counter ui client-sided crash whenever i'm in erebus, but that can be stopped by disabling the ui feature.

-----

**Different mod related minor bug**: In topic about the ui, having **Electroblob's Wizardry** mod installed alongside with this, while holding a magic wand seems to render 3 blank buttons on the right side of the screen when in third person.

**Comment by Abastro** [comment]
Great, it works! Besides, please post the crash report when UI is enabled.

**Comment by Ghostrider231** [comment]
@Abastro 
My Crash report about the UI is actually similar to this issue: https://github.com/Abastro/StellarAPI/issues/13

Similar Crash report output.

**Comment by Abastro** [comment]
Okay. Oops, again.

**Comment by Abastro** [comment]
Try the latest Stellar API, 1.12.2-0.4.2.9.

**Comment by Ghostrider231** [comment]
@Abastro 
It seems to work! It no longer gives me an infinite crash! 

By the way, should I post the three blank buttons GUI bug in a separate issue report?

Otherwise, here's the issue:

-------------------

With **Electroblob's Wizardry** Installed, holding a wand which shows the selected spell gui in thirdperson also shows three blank buttons. Which those are suppose to represent the 'Overlay' 'Main' 'Playing' Buttons. This bug persists unless I've switched to 'Main' to 'Stellar API' which will show me the 'Time Day/Morning/Dawn/or whatever' on my top right of my screen.

**Comment by Abastro** [comment]
Glad it worked! And yes, open a new issue, please. It's a different issue.
