### ISSUE TITLE
Issue with The Betweenlands

### ISSUE THREAD

**Issue by The-Order** [Abastro/StellarAPI#11]
Using All the Mods 3 mod pack for 1.12.2 with StellarAPI only added to the pack. I use it to force the day/night cycles to be longer.

With this mod in the pack it causes an issue with the The Betweenlands mod when using the portal to warp to the dimension. Instead of loading the into dimension's ID, it teleports the player to another part of the overworld and replaces the chunks with the biomes/blocks etc from The Betweenlands mod. It doesn't actually change dimensions such as when going to nether. Using the portal to go back just resets the "overworld" back to the normal chunks.

Removing this mod solves the issue and the portal actually loads the correct dimension.

**Comment by Abastro** [comment]
Oh wow, IDK how could this happen. I'll try to find why, and fix this issue.

**Comment by Abastro** [comment]
Please try 0.4.2.8 when it comes out.

**Comment by Abastro** [comment]
Please reply, or this will be closed in a week.

**Comment by Abastro** [comment]
Already over a week...
