### ISSUE TITLE
Crash on entering Nether

### ISSUE THREAD

**Issue by roppenheim** [Abastro/StellarAPI#13]
Sorry if I'm doing this wrong; I got a null pointer exception on my SSP world upon entering the Nether, and it now crashes every time I re-enter. The crash report went as follows: 
[crash-2018-05-30_22.24.01-client.txt](https://github.com/Abastro/StellarAPI/files/2056427/crash-2018-05-30_22.24.01-client.txt)
And here's the latest log from the logs folder:
[latest.log](https://github.com/Abastro/StellarAPI/files/2056440/latest.log)
Sorry if this isn't anything to do with StellarAPI, it just mentioned it quite a few times. I tried disabling the mod's GUI elements in the config to no avail.

**Comment by Abastro** [comment]
Oops.

**Comment by Abastro** [comment]
Try the latest Stellar API, 1.12.2-0.4.2.9.

**Comment by roppenheim** [comment]
It works! Thanks so much, I really missed Photoptics and Stellar Sky.
