### ISSUE TITLE
Mod conflict.

### ISSUE THREAD

**Issue by LucyFirr** [Abastro/StellarAPI#15]
Hey, sorry to be a pain, but when using the Betweenlands version: 3.3.10 and stellar API 1.12.2 There seems to be an immense issue.

If both mods are installed and you die within the betweenlands dimension, you begin to spazz out and teleport between where you died and where the spawn point in the dimension is. It also messes up the sky but i think that is the lesser of the issues.

oh and i think i am on forge 14.23.4.2729

**Comment by Abastro** [comment]
Are you on the latest version? I thought related bugs are fixed.

**Comment by Abastro** [comment]
Well if you're getting it from other sources than curseforge:
http://stopmodreposts.org/

**Comment by LucyFirr** [comment]
No, i got it off curseforge, and i believe its the latest version. sorry
I will doublecheck though

**Comment by LucyFirr** [comment]
Nevermind, i am even dumber than previously imagined, I had got the update prior to the latest and cause they were the same day and i am god awful at being any kind of smart, i thought i had the right one, just checked all the mods it was breaking with the latest one, and its all fixed, sorry for wasting your time

**Comment by Abastro** [comment]
It's okay.
