### ISSUE TITLE
Sponge compatibility - crash on start up with stellar sky

### ISSUE THREAD

**Issue by ruyanve** [Abastro/StellarAPI#2]
Using Forge 1954
Sponge 1418
Stellar Api 0.4.3.2b

Gets me this: https://gist.github.com/ruyanve/e9138db618f5d477ac2583d70dfcc552

If I drop Stellar Sky 0.4.4.1 into the mix I get the following: https://gist.github.com/ruyanve/43ce5a9bbc16284490bc591221eb6915

**Comment by Abastro** [comment]
Oh, Sponge is calling WorldEvent.Load before the overworld is initialized, where it shouldn't.

**Comment by ruyanve** [comment]
Fixed on Sponge side, thank you! :-)
LOVE your stuff btw <3
