### ISSUE TITLE
Crash: Invalid hand null - 1.9.4

### ISSUE THREAD

**Issue by kirothos** [Abastro/StellarAPI#4]
I get a java.lang.IllegalArgumentException: Invalid hand null when attempting to create a new world with just Stellar API on Minecraft 1.9.4
Forge Version: 12.17.0.1965
StellarAPI Version: 0.4.3.2
Crash log: http://pastebin.com/LXgvvFpa

**Comment by Abastro** [comment]
Update Stellar API. (There is b version)

**Comment by kirothos** [comment]
Curse forge shows the latest version for 1.9.4 as the broken version in the "Recent Files" section.  I see the b version now when I browse files.  Sorry for the confusion.

**Comment by Abastro** [comment]
What a Curse forge... I'd not use that versioning after this time.
