### ISSUE TITLE
Stellar API 0.1.3.8 crashes on "Injecting Stellar Manager"

### ISSUE THREAD

**Issue by Volxx** [Abastro/StellarAPI#5]
Well, here we are again...

So now, after testing out Stellar Skies, I decided to use it with the rest of my mods because it looked really cool. But now when I go into my world, it says "Injecting Stellar Manager" and then crashes.

From the looks of the crash report, it looks like it's coming from Stellar API. I tried recreating the whole directory and replacing Stellar API, but no luck there. I also noticed it said Stellarium in there, which I can understand because I used to have Stellarium in there before I got rid of it because it was erroring.

Crash report: http://pastebin.com/mQAgDG8n
Logs: http://pastebin.com/b0rBBkjg

If you know why this is happening, please tell me. Right now, my thoughts are leaning on OptiFine, though. Thanks in advance!

(BTW, really looking forward to when Stellarium is done!)

**Comment by Abastro** [comment]
This is problem with slimevoid's littleblock mod doing some hacking into the world. IT SHOULD NOT CREATE ANY WORLD INSTANCE ON THE WORLDEVENT.LOAD, at least itshould do it at last.
Just remove the mod, I expect there would be tons of replacements.

**Comment by Volxx** [comment]
damn, i really liked that mod. well, if it means i can have stellar skies and all that shit then i can definitely get rid of it. thanks

**Comment by Abastro** [comment]
You would better repot it to the author of the mod.

**Comment by Volxx** [comment]
That I shall do.
