### ISSUE TITLE
[1.12.2] stellar API causes blindness effect to be near-total

### ISSUE THREAD

**Issue by jonqrandom** [Abastro/StellarAPI#9]
forge 14.23.0.2544, stellar API 0.7.4.1.1
these [two imgur shots](https://imgur.com/a/ad27o) show the same blindness effect, one taken with stellar API installed, the other taken during the same potion duration but with only forge installed.
the shot where no grass is visible is the shot with stellar API installed. no other mods were present in the test instance i produced these screenshots in.
if this is intentional, please will you provide a config option to enable vanilla behaviour?

**Comment by Abastro** [comment]
Fixed on the latest version.
